/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/BauerV3Full.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BauerV3Full-transformed.glb')
  return (
    <group {...props} dispose={null} rotation={[0, 1, 0]}>
      <mesh geometry={nodes.Bv3PC.geometry} material={nodes.Bv3PC.material} position={[0, -0.18, -0.68]} rotation={[3.02, 0, 0]} scale={[0.51, 0.45, 0.51]} />
      <mesh geometry={nodes.BV3Faom.geometry} material={nodes.BV3Faom.material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Bv3CoqueExt.geometry} material={materials['Default OBJ']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/BauerV3Full-transformed.glb')
