/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/BauerV3Full.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelTwo(props) {
  const { nodes, materials } = useGLTF('/Testv2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bv3CoqueExt.geometry}
        material={materials["Default OBJ"]}
        rotation={[Math.PI / 2, 0, -Math.PI / 4]}
      />
    </group>
  )
}

useGLTF.preload('/Testv2.glb')
